apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "apps-{{ .Values.env.name }}"
  namespace: {{ .Values.namespace }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.repoUrl }}
    targetRevision: {{ .Values.targetRevision }}
    path: app-charts
    helm:
      valueFiles:
        - "./env-configs/{{ .Values.env.name }}/values.yaml"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
