{{- range $ws, $apps := .Values.workstreamapps -}}
  {{- range $app := $apps -}}
    {{- $filename := split "." $app -}}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "{{ $ws }}-{{ $filename._0 }}"
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: prod
            url: https://kubernetes.default.svc
            revision: {{ $.Values.env.name }}
  template:
    metadata:
      name: '{{"{{"}}cluster{{"}}"}}-{{ $ws }}-{{ $filename._0 }}'
    spec:
      project: default
      source:
        repoURL: {{ $.Values.repoUrl }}
        targetRevision: '{{"{{"}}revision{{"}}"}}'
        path: helm-charts
        helm:
          valueFiles:
            - "manifests/{{ $ws }}/prod/immutable/{{ $app }}"
            - "app-charts/env-configs/prod/values.yaml"
      destination:
        server: '{{"{{"}}url{{"}}"}}'
        namespace: {{ $.Values.appNamespace }}-ns
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
  {{- end -}}
{{- end -}}
